makefile_skel = """\
# Makefile for GQC workspace
#  This file is generated by GQC and will be overwritten if you run `gqc init-dir --force`.
#  However, it's generally not needed to run that command. So, if you're careful to avoid that,
#  you're free to edit this file however you like.
#
#  Game-as-directory layout (gamequeer#420): every game lives in its own
#  <name>/<name>.gq at this workspace root, not gathered under a flat
#  games/ directory. This Makefile discovers that layout directly (any
#  top-level directory whose own name matches a .gq file inside it) using
#  GNU Make's own $(wildcard)/$(foreach)/$(eval) -- there's no separate
#  generation step to re-run when a game is added or removed; add one with
#  `gqc new <name>` and just run `make` again.

ifndef GQC_CMD
# Assumes `gqc` is installed and on PATH -- e.g. `uv tool install
# /path/to/gamequeer/gqc` (see https://docs.astral.sh/uv/) from a gamequeer
# checkout, which this workspace need not live inside or even near.
# Override this if you're invoking gqc a different way instead, e.g.
# `GQC_CMD := uv run --project /path/to/gamequeer/gqc -m gqc` to run
# straight out of a checkout without installing it as a tool.
GQC_CMD := GQCCMD
endif

BASE_DIR := $(realpath $(shell dirname $(firstword $(MAKEFILE_LIST))))

# Every top-level directory name that contains its own matching entry
# file (<name>/<name>.gq) -- i.e. every game in this workspace. A
# top-level directory that ISN'T a game (assets/, tools/, build/, ...)
# simply has no same-named .gq inside it and is silently skipped.
CANDIDATE_DIRS := $(patsubst $(BASE_DIR)/%/,%,$(wildcard $(BASE_DIR)/*/))
GAME_NAMES := $(foreach d,$(CANDIDATE_DIRS),$(if $(wildcard $(BASE_DIR)/$(d)/$(d).gq),$(d)))
GAME_OUTS := $(foreach g,$(GAME_NAMES),$(BASE_DIR)/build/$(g)/$(g).gqgame)

.PHONY: all clean
.DEFAULT_GOAL := all

all: $(GAME_OUTS)

# One static-pattern-style rule per discovered game: build/<name>/<name>.gqgame
# depends on (only) <name>/<name>.gq -- this Makefile has no visibility into
# a game's assets/ subtree, so it's blind to asset-only changes. If you're
# iterating on assets without touching the .gq source itself, `make clean`
# (or delete that game's build/<name>/ dir) to force a rebuild.
define GAME_RULE
$(BASE_DIR)/build/$(1)/$(1).gqgame: $(BASE_DIR)/$(1)/$(1).gq
\t$$(GQC_CMD) compile -o $(BASE_DIR)/build/$(1) $$<
endef
$(foreach g,$(GAME_NAMES),$(eval $(call GAME_RULE,$(g))))

clean:
\t-rm -rf $(BASE_DIR)/build/*
"""
